### ISSUE TITLE
{"Error creating context 'spring.root': At least one object must implement IComparable."}

### ISSUE THREAD

**Issue by ratheeshpkr** [spring-projects/spring-net#124]
I am getting below error if i include two spring configuration xml file with   PropertyPlaceholderConfigurer. This is happening after migrating from spring 1.3.2 to 2.0.1

`<object type="Spring.Objects.Factory.Config.PropertyPlaceholderConfigurer, Spring.Core">
    <property name="ConfigSections" value="databaseSettings"/>
  </object>`

{"Error creating context 'spring.root': At least one object must implement IComparable."}
InnerException : {"Errored while postprocessing an object factory."}
InnerException : {"Failed to compare two elements in the array."}
Stack trace :    at Spring.Objects.Factory.Config.PropertyResourceConfigurer.PostProcessObjectFactory(IConfigurableListableObjectFactory factory)
   at Spring.Context.Support.AbstractApplicationContext.InvokeObjectFactoryPostProcessors(IList objectFactoryPostProcessors, IConfigurableListableObjectFactory objectFactory)
   at Spring.Context.Support.AbstractApplicationContext.InvokeObjectFactoryPostProcessors(IConfigurableListableObjectFactory objectFactory)
   at Spring.Context.Support.AbstractApplicationContext.Refresh()
   at Spring.Context.Support.XmlApplicationContext..ctor(XmlApplicationContextArgs args)
   at Spring.Context.Support.XmlApplicationContext..ctor(String name, Boolean caseSensitive, String[] configurationLocations)
   at _dynamic_Spring.Context.Support.XmlApplicationContext..ctor(Object[] )
   at Spring.Reflection.Dynamic.SafeConstructor.Invoke(Object[] arguments)
   at Spring.Context.Support.ContextHandler.RootContextInstantiator.InvokeContextConstructor(ConstructorInfo ctor)
   at Spring.Context.Support.ContextHandler.ContextInstantiator.InstantiateContext()
   at Spring.Context.Support.ContextHandler.InstantiateContext(IApplicationContext parentContext, Object configContext, String contextName, Type contextType, Boolean caseSensitive, IList`1 resources)
   at Spring.Context.Support.ContextHandler.Create(Object parent, Object configContext, XmlNode section)

**Comment by thorstenbaek** [comment]
We have the same issue. 
See our pull request: Multiple PropertyPlaceholderConfigurers fail in AbstractObjectFactory #120

**Comment by sbohlen** [comment]
I'll take a look @ the PR later this week.

-Steve B.

-----Original Message-----

**Comment by ratheeshpkr** [comment]
thanks @thorstenbaek. That solved the problem, but hope there will be an official release with this fix.

**Comment by thorstenbaek** [comment]
@sbohlen, did you look into this PR? When can we expect an official release with this fix?

**Comment by sbohlen** [comment]
Hopefully this weekend.  The system on which I'd had the build/test env for this project set up experienced a HD failure and so I've got to rebuild it (along w all the requisite Visual Studio, etc. installs) to return to a fully working state first.

-Steve B.

-----Original Message-----

**Comment by sbohlen** [comment]
Fixed in https://github.com/spring-projects/spring-net/pull/120
