### ISSUE TITLE
why rollbackOnCommitFailure of AbstractPlatformTransactionManager is false default?

### ISSUE THREAD

**Issue by kelvin17** [spring-projects/spring-net#142]
Dear all：  
Recently,I have got a problem. The spring commit transaction  is failed,but the data in MySQL Database is updated.

Generally, We think the data will be rollbacked when transaction commit is failed. 

Then I look at the spring code.
My transactionManager is org.springframework.jdbc.datasource.DataSourceTransactionManager. And we don't set the property named "rollbackOnCommitFailure".So when the commit operation is failed,the spring will not to roolback.

My question is why rollbackOnCommitFailure is false as default in org.springframework.transaction.support.AbstractPlatformTransactionManager whick is superclass of DataSourceTransactionManager？
And when is it not necessary to rollback when commit failed？

Error Stack:
`Caused by: org.springframework.transaction.TransactionSystemException: Could not commit JDBC transaction; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Communications link failure during commit(). Transaction resolution unknown.
        at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:270)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:147)
        at com.alipay.pcapplycore.core.service.command.impl.AsynCmdServiceImpl.lockCommand(AsynCmdServiceImpl.java:120)
        at com.alipay.pcapplycore.core.service.template.impl.CmdExecuteTemplateImpl.execute(CmdExecuteTemplateImpl.java:58)
        ... 17 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Communications link failure during commit(). Transaction resolution unknown.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.Util.getInstance(Util.java:386)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
        at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1664)
        at com.alipay.zdal.datasource.resource.adapter.jdbc.BaseWrapperManagedConnection.jdbcCommit(BaseWrapperManagedConnection.java:492)
        at com.alipay.zdal.datasource.resource.adapter.jdbc.WrappedConnection.commit(WrappedConnection.java:392)
        at com.alipay.zdal.datasource.context.GenericConnectionContext.commit(GenericConnectionContext.java:215)
        at com.alipay.zdal.client.dispatch.connection.DispatchableConnection.commit(DispatchableConnection.java:284)
        at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:267)
        ... 22 more`

**Comment by anshuabhgithub** [comment]
i am also facing same issue

**Comment by lahma** [comment]
I'm doing a rude experiment with closing this, like what stale bot does, but maybe more human as I will probably actually react to feedback. As this issue has been stale for so long, I'll close it. If it's still an issue you would like to pursue, we can definitely reopen. 

With limited resources this is just something that we need to do. Thank you for your understanding.
